name: Link Checker
# Checks sanity of links

on:
    push:
      branches:
        - main
        - actions
    pull_request:
      branches:
        - main
    schedule:
      - cron: '0 19 2 * *' # 19:00 UTC every second day of each month

permissions:
  contents: read
  issues: write # required for peter-evans/create-issue-from-file

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6
        with:
          # Check all markdown, html files in repo
          args: "--verbose './**/*.md' './**/*.sii'"
          # Use makdown as output format (easier to work on issues)
          format: markdown
          # Don't fail action on broken links
          fail: false

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated